//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent_Task
    {
        public int Parent_ID { get; set; }
        public string Parent_Task1 { get; set; }
    }
}
